language: minimal
addons:
  apt:
    update: true
before_script:
- sudo apt-get -y install libxml2-utils
script:
- git checkout $TRAVIS_BRANCH
- . .travis/pull.sh
deploy:
  on:
    condition: $CHANGED = 1
    all_branches: true
  provider: script
  script: .travis/push.sh
  skip_cleanup: true
notifications:
  email:
    on_failure: change
    on_success: always
    recipients:
    - $NOTIFY
